### ISSUE TITLE
Change the license from GPLv3 to MPL v. 2.0

### ISSUE THREAD

**Issue by jkcclemens** [RoyalDev/RoyalCommands#38]
Anyone that has contributed copyrightable code should be asked if they are on board with this change.

- [x] @jkcclemens
- [x] @LordZeroHour

If you are in this list, please respond with whether you are okay with your code that you have contributed to this project being relicensed under MPL v. 2.0 (full text [here](https://www.mozilla.org/MPL/2.0/index.txt)).

**Comment by jkcclemens** [comment]
I am, of course, 100% okay with all of my code being relicensed under the Mozilla Public License v. 2.0.

**Comment by LordZeroHour** [comment]
Kyle,

The decision to re-license to MPL 2.0 sounds like a good decision to me and
I am on board.


Thank you,
Tory
